### ISSUE TITLE
Getting the Flutter app to run.

### ISSUE THREAD

**Issue by sgoudsme** [marcel-cd/flutter_wm_ble_com#1]
Hi,
I would like to get this flutter app running.
I could already build the Wirepas firmware, so that is not a problem.

But, I'm new to flutter and in your README, you point that I should run `flutter pub get`. This command runs successfully.
But the next one `flutter pub run` fails with the error:  `Must specify an executable to run`.

I tried to use the `test/wiget_test.dart` and the `lib/main.dart`, but those commands fail with a lot of build errors. It seems like I'm missing a small thing.

This is maybe because of a version error? I'm using 3.7.8.

Can you point me to the thing I'm missing?

Thank you,
Sibrecht

**Comment by marcel-cd** [comment]
Hello Sibrecht,

Does any Flutter App run on your system? eg. the default counter app?

Marcel

**Comment by sgoudsme** [comment]
Hi Marcel,

Mistake on my side: the command is not `flutter pub run`, but `flutter run`.

I can run the application.
Very interesting project. A good job. thank you.

Remark: In the assets/firmware, there is still a v1.1. When I build with v1.2 and restart, the update works just fine.

Regards,
Sibrecht
